name: "Workflow Commands"

on: ['push']

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: "Group loggin"
        run: |
          echo "My Group Message"
          echo "Msg 1"
          echo "Msg 2"
          echo "::engroup::"
      - name: "step 1"
        run: |
          echo "MY_VAL=hello" >> $GITHUB_ENV
      - name: "step 2"
        run: |
          echo $MY_VAL